apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-oxln
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-oxln
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-python-basic-oxln
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: python-app
    app.kubernetes.io/instance: devfile-sample-python-basic-oxln
status:
  loadBalancer: {}
