apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-mepz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-mepz
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-mepz
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-mepz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-mepz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-qvdf-tenant/appstudio/dc-metro-map-mepz@sha256:fc07d40f51edfee9947d59e0eca42100ec705539e3cf2757e727bd188ee64d68
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 25Mi
status: {}
